environment:
  name: "TwoArmPickPlace"
  obs_length: 1
  action_length: 1
  visualize_eval_runs: false

algorithm:
  name: "BC"
  model:
    name: "MLP"
    params:
      hidden_sizes: [256, 512, 256]
      activation: "ReLU"
      output_activation: null
  optimizer:
    name: "Adam"
    params:
      lr: 0.0001
  loss:
    - name: "MSELoss"
      weight: 1.0

dataset:
  hdf5_path: "wp/Panda_Panda_TwoArmPickPlace_2025-01-02_17-10-41/demo.hdf5"
  uses_state_obs: false
  uses_image_obs: false
  specific_obs_keys:
    - "robot0_eef_pos"
    - "robot0_eef_quat"
    - "robot1_eef_pos"
    - "robot1_eef_quat"
    - "hammer_pos"
    - "hammer_quat"
    - "bin_pos"
    - "bin_quat"
    - "robot0_gripper_qpos"
    - "robot1_gripper_qpos"
  split_ratio: 0.8
  batch_size: 64

training:
  num_epochs: 500
  num_epochs_logging: 10
  num_episodes_eval: 2


seed: 42
model_out_dir: "bc_mlp_two_arm_pick_place"
log_dir: "bc_mlp_two_arm_pick_place"
wandb:
  log: true
  project: "imitation_learning"