environment:
  name: "TwoArmLift"
  obs_length: 1
  action_length: 1
  visualize_eval_runs: false

policy:
  name: "BC"
  params:
    model:
      name: "MLP"
      params:
        hidden_sizes: [256, 256]
        activation: "ReLU"
        output_activation: null
    optimizer:
      name: "Adam"
      params:
        lr: 0.001
    loss:
      - name: "MSELoss"
        weight: 1.0

dataset:
  hdf5_path: "wp/Panda_Panda_TwoArmLift_2025-01-08_14-46-48/demo.hdf5"
  uses_state_obs: false
  uses_image_obs: false
  specific_obs_keys:
    - "robot0_eef_pos"
    - "robot0_eef_quat"
    - "robot1_eef_pos"
    - "robot1_eef_quat"
    - "robot0_gripper_qpos"
    - "robot1_gripper_qpos"
    - "handle0_xpos"
    - "handle1_xpos"
    - "pot_quat"
  split_ratio: 0.8
  batch_size: 64

training:
  num_epochs: 300
  num_epochs_eval: 10
  num_episodes_eval: 2

seed: 42
model_out_dir: "bc_mlp_two_arm_lift"
log_dir: "bc_mlp_two_arm_lift"
wandb:
  log: true
  project: "imitation_learning"